# Generated by Django 2.1 on 2019-01-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190128_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_text',
        ),
    ]
